### PR TITLE
Add comments because wenyuan told me to analyse code

### PR DESCRIPTION
**Pull request by AV306**

### CODE REVIEW

**Comment by AV306** [comment]
I am unable to can TypeScript anymore :(

**Comment by AV306** [comment]
Oops

**Comment by AV306** [comment]
@AJR07

**Comment by AJR07** [comment]
Can you try too resolve the ??? ones tho, any thing that u dont understand u can pm me. Then ill merg :D

**Comment by AV306** [comment]
Ok :D

**Comment by AV306** [comment]
Done till coinflip

**Comment by AJR07** [comment]
Thanks :))) You deserve the merge

**Comment by AV306** [comment]
Oh noooooo when @erratic-c-programmer refactored he didn’t change the file headers 
😭

**Comment by AV306** [comment]
Ah well
Nevermind

**Comment by AJR07** [comment]
You can make another pr to fix it if u want to

**Comment by tux314159** [comment]
@AV306 pretty sure file headers aren’t necessary

this is a very simple codebase and I’d argue if you can’t tell what a file does from a quick glance we’re doing something wrong :p

**Pull request merged**
