### PR TITLE
Comment convertcase.ts

### PR DESCRIPTION
**Pull request by AV306**
Why u guys like to do this:

Something =>
     Something_else
       .some_method()

I mean its fine but for readability…

### CODE REVIEW

**Comment by AV306** [comment]
@AJR07 :(((((

**Comment by tux314159** [comment]
Looks alright I think but could you please rewrite the history a bit? As DEVELOPING.md (hint hint soon to be called HACKING.md :)) says you should never merge Beta into everything but you should rebase... if we merge this as-is the history would become an even bigger mess

**Comment by tux314159** [comment]
also,
> Why u guys like to do this:
> 
> Something =>
> Something_else
> .some_method()
>
> I mean its fine but for readability…

It's enforced by prettier. Nothing we can do about it.

**Comment by AJR07** [comment]
> Why u guys like to do this:
> 
> Something =>
> Something_else
> .some_method()
> 
> I mean its fine but for readability…

The reason we do this is because we think it looks a lot more readable? like u can see the object ur applying the method too directly above

**Comment by tux314159** [comment]
Also, since this PR is nothing but VERY QUESTIONABLE style changes  (USE PRETTIER AND FOLLOW K&R/OTBS PLEASE!!!)and very strange comments, I'm gonna close it...

**Comment by AJR07** [comment]
😲

**Comment by tux314159** [comment]
For example,
```
function( arg1, arg2 ) // BAD
function(arg1, arg2) // GOOD
switch ( thing ) ... // BAD
switch (thing) ... // GOOD
```

And please DO NOT have comments explaining _style_!!!
like this one:
```     switch ( subcommand ) { // put it INLINE```

**Comment by AV306** [comment]
Hmmm ok
Sorry wasn’t in the best of moods then :(
Also I thought you leave spaces between braces and arguments for readability? Some guides tell me to do that

**Comment by tux314159** [comment]
Those guides are wrong!!!!!!
just kidding but I personally don't like that at all and I don't think our dev team does either :p 
as we said
USE K&R (OTBS?)
USE PRETTIER

**Comment by AJR07** [comment]
> Hmmm ok
> Sorry wasn’t in the best of moods then :(
> Also I thought you leave spaces between braces and arguments for readability? Some guides tell me to do that
Ah, its fine we have our own style guide. U can keep contributing, as long as it helps we will merge :)

**Comment by AV306** [comment]
ok :)
ps idk how/what linter is so i dun use it

**Comment by AJR07** [comment]
What u can do is install prettier here https://prettier.io for npm, and prettify the code before u submit. Generally prettified code should fit the style guide

**Pull request closed without merging**
