### PR TITLE
Patch some stuff in coinside

### PR DESCRIPTION
**Pull request by AV306**
I messed up a little...
Not major changes, noticed a bug in the embed reply tho

### CODE REVIEW

**Comment by tux314159** [comment]
Hi I don't think you quite understood the (wrong) code :P I'll merge if you fix it thanks
If not I'll probably just fix it myself anyway :p

**Comment by tux314159** [comment]
actually ye I'm gonna just fix it myself
the "Fix flaw in coinside logic" is flawed lol cos you misunderstood code
(EDIT: maybe not, I'm not sure but it's too cluttered for my taste anyway)
(EDITx2: yeah something wrong with the code LOL what even is "coinside" why is it called that
and WHY THE TENARY STATEMENT xD like you basically did `a === b ? true : false` bruh

**Comment by AV306** [comment]
...it wasn’t that cluttered yesterday...
no, the main thing is that the amount earned should be multiplier - 1 because you’re multiplying it. That was kind of what I was trying to fix so well it’s still not fixed...
Also coinside was meant to be a special “edge” case (literally) that would override normal coinflip (like a real coin landing on its edge) but ok I won’t question anymore

**Comment by tux314159** [comment]
HAHAHAHAHA ok that makes sense about the coinside xD
But the *code* was **very** cluttered honestly, you can tell at first glance-- it's way too long for something so simple lol

**Comment by tux314159** [comment]
But I don't really agree with that mechanic though-- but I wouldn't mind giving the user a THIRD option, on the edge, and if correct then jackpot
But definitely not unconditional jackpot on landing on edge

@AV306 @AJR07 what do you guys think?

**Comment by AV306** [comment]
Ok, but irl you don't really bet on the coin landing on the edge (since it almost never happens)
I'm fine with jackpot requiring both the bet to be correct and the coin to land on its edge!

**Comment by tux314159** [comment]
alright then

**Pull request closed without merging**
